#!/usr/bin/env bash
#
# Generate the permanent Blockhold Defense signing key.
#
# WHY YOU NEED THIS
# -----------------
# Android identifies an app by (package name + signing certificate). An update is only
# accepted when the new APK is signed by the EXACT same key as the installed one; otherwise
# the installer refuses with INSTALL_FAILED_UPDATE_INCOMPATIBLE ("App not installed").
#
# Creating a new key does NOT let you update over an existing install - it guarantees you
# cannot. Whatever key you use, you must uninstall the currently installed build once. After
# that, every future APK signed with THIS key updates cleanly, with progress preserved.
#
# Keys currently in play for ai.techtroy.blockhold:
#   14d77995...  "CN=Blockhold Defense, OU=Game Release"        v1.0 (private key not in repo)
#   095f279b...  "CN=Blockhold Defense Debug, OU=Sideload"      v1.1 + v1.2 (private key not in repo)
#   (per-machine) ~/.android/debug.keystore                     Gradle assembleDebug / CI
#
# Neither private key is in this workspace, so no build made here can update an existing
# install. This script creates the key that ends that problem for good.
#
# BACK IT UP. Lose it and every player has to uninstall and lose progress again.
#
# Usage:
#   ./scripts/make-signing-key.sh                 # prompts for a password
#   BLOCKHOLD_STORE_PASS=... ./scripts/make-signing-key.sh --non-interactive

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

SIGNING_DIR=".signing"
KEYSTORE="$SIGNING_DIR/blockhold-release.p12"
PROPS="$SIGNING_DIR/release.properties"
ALIAS="blockhold"
DNAME="CN=Blockhold Defense, OU=Game Release, O=TechTroyAi, L=Davao City, ST=Davao Region, C=PH"
VALIDITY_DAYS=10950   # 30 years; must outlive the app

if ! command -v keytool >/dev/null 2>&1; then
  echo "error: keytool not found. Install a JDK 17 (Temurin, or Android Studio's bundled JBR)." >&2
  exit 1
fi

if [[ -f "$KEYSTORE" ]]; then
  echo "error: $KEYSTORE already exists." >&2
  echo "       Refusing to overwrite - that would break updates for anyone already installed." >&2
  echo "       Delete it deliberately if you really mean to start over." >&2
  exit 1
fi

if [[ "${1:-}" == "--non-interactive" ]]; then
  STORE_PASS="${BLOCKHOLD_STORE_PASS:?set BLOCKHOLD_STORE_PASS for --non-interactive}"
else
  read -r -s -p "New keystore password (min 6 chars, save it somewhere safe): " STORE_PASS; echo
  read -r -s -p "Repeat password: " STORE_PASS_CONFIRM; echo
  if [[ "$STORE_PASS" != "$STORE_PASS_CONFIRM" ]]; then
    echo "error: passwords do not match." >&2
    exit 1
  fi
fi

if [[ ${#STORE_PASS} -lt 6 ]]; then
  echo "error: password must be at least 6 characters." >&2
  exit 1
fi

mkdir -p "$SIGNING_DIR"
chmod 700 "$SIGNING_DIR"

keytool -genkeypair \
  -alias "$ALIAS" \
  -keyalg RSA \
  -keysize 4096 \
  -sigalg SHA256withRSA \
  -validity "$VALIDITY_DAYS" \
  -dname "$DNAME" \
  -keystore "$KEYSTORE" \
  -storetype PKCS12 \
  -storepass "$STORE_PASS" \
  -keypass "$STORE_PASS"

cat > "$PROPS" <<EOF
# Generated by scripts/make-signing-key.sh - never commit this file.
storePassword=$STORE_PASS
keyAlias=$ALIAS
keyPassword=$STORE_PASS
EOF
chmod 600 "$PROPS" "$KEYSTORE"

echo
echo "Created:"
echo "  $KEYSTORE"
echo "  $PROPS"
echo
echo "Certificate fingerprint (record this in artifacts/README.md for every release):"
keytool -list -v -keystore "$KEYSTORE" -storepass "$STORE_PASS" -alias "$ALIAS" \
  | grep -E 'SHA256:|Valid from' || true

echo
echo "Next:"
echo "  1. ./gradlew assembleRelease"
echo "     -> app/build/outputs/apk/release/app-release.apk  (AGP zipaligns and v2+v3 signs it)"
echo "  2. python3 scripts/verify-apk.py app/build/outputs/apk/release/app-release.apk"
echo "  3. UNINSTALL Blockhold Defense on the device once, then install this APK."
echo "     Every later build signed with this key will update in place."
echo
echo "  For CI, add these GitHub repository secrets:"
echo "     BLOCKHOLD_KEYSTORE_BASE64  =  base64 -w0 $KEYSTORE"
echo "     BLOCKHOLD_STORE_PASSWORD   =  the password you just entered"
echo "     BLOCKHOLD_KEY_ALIAS        =  $ALIAS"
echo
echo "  BACK UP $KEYSTORE and the password to two separate encrypted locations."
echo "  $SIGNING_DIR/ is gitignored - it must never be committed."
